"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

const labels={DRAFT:"แบบร่าง",PENDING:"รอตรวจ",APPROVED:"เปิดขายแล้ว",REJECTED:"ต้องแก้ไข"};
export default function MyDesigns(){const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const load=()=>fetch("/api/designs").then(r=>r.json()).then(j=>setItems(j.data||[])).finally(()=>setLoading(false));useEffect(()=>{load()},[]);
 async function action(url,method,id){setMessage("");const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const j=await r.json();if(!r.ok)return setMessage(j.error);setMessage("บันทึกเรียบร้อย");load()}
 return <div><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold">แบบเสื้อของฉัน</h1><p className="mt-1 text-sm text-slate-500">สร้างแบบ ส่งตรวจ และติดตามสถานะการเปิดขาย</p></div><Link href="/custom" className="rounded-xl bg-black px-4 py-2 text-sm text-white">ออกแบบเสื้อใหม่</Link></div>{message&&<p className="mb-4 rounded-xl bg-slate-100 p-3 text-sm">{message}</p>}{loading?<p>กำลังโหลด…</p>:items.length===0?<div className="rounded-2xl border p-10 text-center text-slate-500">ยังไม่มีแบบเสื้อ</div>:<div className="grid gap-4 md:grid-cols-2">{items.map(p=><article key={p.id} className="flex gap-4 rounded-2xl border p-4"><img src={p.images[0]} alt={p.name} className="h-28 w-24 rounded-xl object-cover"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><h2 className="truncate font-semibold">{p.name}</h2><span className="shrink-0 rounded-full bg-slate-100 px-2 py-1 text-xs">{labels[p.approvalStatus]}</span></div>{p.approvalStatus==="APPROVED"&&<p className="mt-2 font-bold">฿{p.price.toLocaleString("th-TH")}</p>}{p.rejectionReason&&<p className="mt-2 text-xs text-red-600">เหตุผล: {p.rejectionReason}</p>}<div className="mt-4 flex flex-wrap gap-2">{["DRAFT","REJECTED"].includes(p.approvalStatus)&&<button onClick={()=>action("/api/designs/submit","POST",p.id)} className="rounded-lg bg-black px-3 py-1.5 text-xs text-white">ส่งตรวจ</button>}{p.approvalStatus==="PENDING"&&<button onClick={()=>action("/api/designs/submit","DELETE",p.id)} className="rounded-lg border px-3 py-1.5 text-xs">ถอนคำขอ</button>}{p.approvalStatus!=="PENDING"&&<button onClick={()=>confirm("ลบแบบนี้หรือไม่?")&&action("/api/designs","DELETE",p.id)} className="rounded-lg border border-red-200 px-3 py-1.5 text-xs text-red-600">ลบ</button>}</div></div></article>)}</div>}</div>}
