import { NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { requireAdmin } from "@/lib/auth/dal";
import { HttpError } from "@/lib/http";
import { deleteImage, storageKeyFromUrl } from "@/lib/storage";

const fail=e=>e instanceof HttpError?NextResponse.json({error:e.message},{status:e.status}):NextResponse.json({error:"เกิดข้อผิดพลาด"},{status:500});
export async function GET(){try{await requireAdmin();const data=await prisma.product.findMany({where:{is_custom:true},include:{seller:{select:{name:true,email:true}}},orderBy:{updatedAt:"desc"}});return NextResponse.json({data});}catch(e){return fail(e)}}
export async function PATCH(request){try{const admin=await requireAdmin(),b=await request.json(),id=Number(b.id);if(!["APPROVED","REJECTED"].includes(b.status))return NextResponse.json({error:"สถานะไม่ถูกต้อง"},{status:400});const p=await prisma.product.findUnique({where:{id}});if(!p?.is_custom)return NextResponse.json({error:"ไม่พบแบบเสื้อ"},{status:404});if(b.status==="APPROVED"){const price=Number(b.price),stock=Number(b.stock);if(!Number.isInteger(price)||price<1||!Number.isInteger(stock)||stock<0)return NextResponse.json({error:"ราคาและสต็อกไม่ถูกต้อง"},{status:400});const data=await prisma.product.update({where:{id},data:{price,stock,approvalStatus:"APPROVED",is_public:true,reviewedAt:new Date(),reviewedById:admin.id,rejectionReason:null}});return NextResponse.json({data})}const reason=String(b.reason||"").trim();if(reason.length<3)return NextResponse.json({error:"กรุณาระบุเหตุผลที่ปฏิเสธ"},{status:400});const data=await prisma.product.update({where:{id},data:{approvalStatus:"REJECTED",is_public:false,reviewedAt:new Date(),reviewedById:admin.id,rejectionReason:reason}});return NextResponse.json({data});}catch(e){return fail(e)}}
export async function DELETE(request){try{await requireAdmin();const{id}=await request.json();const p=await prisma.product.findUnique({where:{id:Number(id)},include:{_count:{select:{orderItems:true}}}});if(!p)return NextResponse.json({error:"ไม่พบสินค้า"},{status:404});if(p._count.orderItems)return NextResponse.json({error:"สินค้านี้มีประวัติการขายแล้ว ให้ระงับแทนการลบ"},{status:409});await prisma.product.delete({where:{id:p.id}});for(const url of p.images)await deleteImage(storageKeyFromUrl(url));return NextResponse.json({success:true});}catch(e){return fail(e)}}
