import { Anuphan } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import NavbarA from "@/components/ui/NavbarA";

const anuphan = Anuphan({
  variable: "--font-anuphan",
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="th"
      className={`${anuphan.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex min-h-screen flex-col">
        <AuthProvider>
          <NavbarA />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
