ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PAYMENT_EXPIRED';
ALTER TABLE "payments" ADD COLUMN "qr_code_url" TEXT;
ALTER TABLE "payments" ADD COLUMN "expires_at" TIMESTAMP(3);
